### ISSUE TITLE
Release 0.2.0

### ISSUE THREAD

**Issue by yuya-takeyama** [yuya-takeyama/rack-graphiql#4]
## TODO

* [x] Review and merge https://github.com/yuya-takeyama/rack-graphiql/pull/3
* [x] Make `CHANGELOG.md`
* [x] Automate releasing to RubyGems.org using GitHub Actions
* [x] Add @bnadlerjr to the owners of the gem

**Comment by yuya-takeyama** [comment]
Released:
https://rubygems.org/gems/rack-graphiql

**Comment by yuya-takeyama** [comment]
@bnadlerjr 
I've sent an invitation to you:
![image](https://user-images.githubusercontent.com/241542/151719674-b432a488-7bb9-447c-8c31-ae15bc55d829.png)

**Comment by bnadlerjr** [comment]
Thank you! I just confirmed it.
